### ISSUE TITLE
No data available in table

### ISSUE THREAD

**Issue by naveen1583** [jmpsec/osctrl#440] opened 2024-07-02 00:00 UTC
Hello, 

UI doesn't show anything, but I can the query data in the docker container logs including the query id. Is this a bug or am I missing something?

Thank you!

**Comment by naveen1583** [comment] 2024-07-02 20:29
Ah, do you have a fix/work around yet?

**Comment by naveen1583** [comment] 2024-07-02 20:35
@peterbogdan 
I also see the following errors in two containers, if you have any idea.

 osctrl-tls-dev:

[20:25:34] building...
[20:25:37] running...
main.go:510: Initializing backend...
main.go:515: Connection to backend successful!
main.go:528: Initializing cache...
main.go:533: Connection to cache successful!
main.go:545: Initialize environment
main.go:547: Initialize settings
main.go:549: Initialize nodes
main.go:551: Initialize tags
main.go:553: Initialize queries
main.go:555: Initialize carves
main.go:557: Loading service settings
settings.go:489: SetString 0.0.0.0 tls json_listener
settings.go:489: SetString 9000 tls json_port
settings.go:489: SetString 0.0.0.0 tls json_host
settings.go:489: SetString none tls json_auth
settings.go:489: SetString stdout tls json_logger
settings.go:489: SetString  tls json_carver
main.go:562: Loading service metrics
main.go:568: Initialize ingested
main.go:571: Loading TLS logger
stdout.go:24: No stdout logging settings
main.go:580: Preparing pseudo-cache for environments
main.go:597: Preparing pseudo-cache for settings
main.go:682: osctrl-tls v0.3.6 - HTTP listening 0.0.0.0:9000

2024/07/02 20:25:37 /usr/src/app/settings/settings.go:379 record not found
[5.515ms] [rows:0] SELECT * FROM "setting_values" WHERE (json = false AND service = 'tls' AND environment_id = 0) AND name = 'refresh_settings' AND "setting_values"."deleted_at" IS NULL ORDER BY "setting_values"."id" LIMIT 1
utils.go:42: Refreshing environments...
utils.go:53: Refreshing settings...

2024/07/02 20:26:14 /usr/src/app/environments/environments.go:114 record not found
[5.822ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '0d46a882-3cfb-4d12-b8a3-203098e4d551' OR uuid = '0d46a882-3cfb-4d12-b8a3-203098e4d551') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:26:17 /usr/src/app/environments/environments.go:114 record not found
[0.831ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '5605fd60-aa9b-463b-a4cb-712386b3f333' OR uuid = '5605fd60-aa9b-463b-a4cb-712386b3f333') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:27:14 /usr/src/app/environments/environments.go:114 record not found
[0.984ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '0d46a882-3cfb-4d12-b8a3-203098e4d551' OR uuid = '0d46a882-3cfb-4d12-b8a3-203098e4d551') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:27:17 /usr/src/app/environments/environments.go:114 record not found
[0.789ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '5605fd60-aa9b-463b-a4cb-712386b3f333' OR uuid = '5605fd60-aa9b-463b-a4cb-712386b3f333') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:28:02 /usr/src/app/environments/environments.go:114 record not found
[0.773ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '5605fd60-aa9b-463b-a4cb-712386b3f333' OR uuid = '5605fd60-aa9b-463b-a4cb-712386b3f333') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:323: error getting environment record not found

2024/07/02 20:28:14 /usr/src/app/environments/environments.go:114 record not found
[0.744ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '0d46a882-3cfb-4d12-b8a3-203098e4d551' OR uuid = '0d46a882-3cfb-4d12-b8a3-203098e4d551') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:28:17 /usr/src/app/environments/environments.go:114 record not found
[0.769ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '5605fd60-aa9b-463b-a4cb-712386b3f333' OR uuid = '5605fd60-aa9b-463b-a4cb-712386b3f333') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:29:12 /usr/src/app/environments/environments.go:114 record not found
[0.793ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '0d46a882-3cfb-4d12-b8a3-203098e4d551' OR uuid = '0d46a882-3cfb-4d12-b8a3-203098e4d551') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:323: error getting environment record not found

2024/07/02 20:29:14 /usr/src/app/environments/environments.go:114 record not found
[0.974ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '0d46a882-3cfb-4d12-b8a3-203098e4d551' OR uuid = '0d46a882-3cfb-4d12-b8a3-203098e4d551') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

2024/07/02 20:29:17 /usr/src/app/environments/environments.go:114 record not found
[0.783ms] [rows:0] SELECT * FROM "tls_environments" WHERE (name = '5605fd60-aa9b-463b-a4cb-712386b3f333' OR uuid = '5605fd60-aa9b-463b-a4cb-712386b3f333') AND "tls_environments"."deleted_at" IS NULL ORDER BY "tls_environments"."id" LIMIT 1
handlers.go:469: error getting environment record not found

and osctrl-postgres-dev container:

2024-07-02 20:33:46.388 UTC [559] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:33:46.396 UTC [560] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:33:46.396 UTC [560] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:33:46.404 UTC [561] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:33:46.404 UTC [561] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:33:56.436 UTC [569] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:33:56.436 UTC [569] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:33:56.444 UTC [570] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:33:56.444 UTC [570] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:33:56.455 UTC [571] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:33:56.455 UTC [571] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:06.489 UTC [581] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:06.489 UTC [581] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:06.499 UTC [582] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:06.499 UTC [582] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:06.509 UTC [589] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:06.509 UTC [589] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:16.536 UTC [592] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:16.536 UTC [592] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:16.546 UTC [593] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:16.546 UTC [593] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:16.559 UTC [600] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:16.559 UTC [600] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:26.587 UTC [602] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:26.587 UTC [602] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:26.597 UTC [609] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:26.597 UTC [609] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"
2024-07-02 20:34:26.604 UTC [610] FATAL:  password authentication failed for user "osctrl"
2024-07-02 20:34:26.604 UTC [610] DETAIL:  Password does not match for user "osctrl".
	Connection matched pg_hba.conf line 99: "host all all all md5"

**Comment by peterbppb** [comment] 2024-07-03 15:24
did not find any work-around yet

the errors I have are in `osctrl-admin-dev` container

**Comment by peterbogdan** [comment] 2024-07-03 15:26
did not find any work around yet

the errors I have are in `osctrl-admin-dev` container

**Comment by javuto** [comment] 2024-07-06 17:35
This is a duplicate of #438

**Closed by javuto** 2024-07-06 17:35 UTC
Labels: 🐛 bug, duplicate, osctrl-admin
