### ISSUE TITLE
Quick Enroll on a Ubuntu 18.04 node does not result in enroll.sh download and install.

### ISSUE THREAD

**Issue by avinashkurup** [jmpsec/osctrl#71] opened 2020-05-14 08:49 UTC
Hi Javier,
    I have deployed osctrl using, make docker_all. I have created a new environment (and copied the certificates of the dev environment) using the admin interface. I was attempting to enroll an Ubuntu 18.04.3 LTS using the quick-enroll method. On running the enrollment link using curl, agent (enroll.sh) does not download and install. I have attached the logs generated by each container as well as the curl on the remote machine. I would like to add that the system is on the local network and accessible as the logs show. Please help me with this.
[osctrl-enroll-file-download-fail-issue.txt](https://github.com/jmpsec/osctrl/files/4627055/osctrl-enroll-file-download-fail-issue.txt)

**Comment by avinashkurup** [comment] 2020-05-15 07:38
Hi Javier,
     Can you please confirm this is still an issue?.

**Comment by javuto** [comment] 2020-05-15 20:14
Hi Avinash,

Thanks for reporting this issue. I have reproduced the problem and I am working on a fix. As soon as it is ready, I will let you know!

**Comment by javuto** [comment] 2020-05-15 21:22
Can you provide also the logs from `osqueryd`? Just to discard that there is also a certificate verification problem. Thanks!

**Comment by javuto** [comment] 2020-05-16 20:57
I have merged the fix for this problem, can you please confirm it has been resolved? Thanks!

**Comment by avinashkurup** [comment] 2020-05-17 23:25
HI Javier,
     Thank you. I just pulled the latest changes and tried the quick enroll after generating certificates in osctrl. I still don't get the enroll script downloaded and running on my client. (I have not installed osqueryd on client). I have however provided the curl verbose and osctl logs. Please check.
[logs.txt](https://github.com/jmpsec/osctrl/files/4641277/logs.txt)

**Comment by javuto** [comment] 2020-05-17 23:51
Those logs indicate that the service `osctrl-tls` has not been deployed correctly since it is missing some files:

```
osctrl-tls          | handlers.go:537: error getting script open scripts/quick-add.sh: no such file or directory
```

**Comment by avinashkurup** [comment] 2020-05-18 04:05
Hi Javier,
    Could you please tell me how I could fix the above issue. I find this in the beginning of the logs, is it related ? Please look at the logs, I find the tls containers created successfully.

[osctrl-full-log.txt](https://github.com/jmpsec/osctrl/files/4641930/osctrl-full-log.txt)

Can't load /home/avinash_kurup/.rnd into RNG
139807317397952:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/avinash_kurup/.rnd
Generating a RSA private key
...........+++++
...............................................+++++
writing new private key to 'deploy/docker/certs/osctrl.key'
-----

**Comment by javuto** [comment] 2020-05-18 07:25
This seems to be an issue with your system and `openssl`, and the certificate (as the logs show further down) is not generated so osquery can not talk to `osctrl`. Check out this issue, it may help you solve this problem: https://github.com/openssl/openssl/issues/7754

**Comment by avinashkurup** [comment] 2020-05-18 13:52
I fixed the above issue, using this fix. https://github.com/openssl/openssl/issues/7754#issuecomment-586713820

Now i dont see the error in the logs.
[+] Preparing certificates for osctrl-nginx
[+] Generating deploy/docker/certs/osctrl.key and deploy/docker/certs/osctrl.crt
Generating a RSA private key
........................................+++++
..........................................................+++++
writing new private key to 'deploy/docker/certs/osctrl.key'

Unfortunately, i still see the errors 
osctrl-tls          | handlers.go:537: error getting script open scripts/quick-add.sh: no such file or directory

and the enroll.sh script does not download and install. I am now testing this on a physical machine. Osquery is installed and running on the machine.

**Comment by javuto** [comment] 2020-05-18 18:11
Just merged a small change to fix the `osctrl-tls` issue where the template for the quick-enroll script was missing in that container. Please check if that fixed the issue. Thanks!

**Closed** 2020-05-18 18:11 UTC
Labels: bug, deployment

**Comment by avinashkurup** [comment] 2020-05-18 23:12
Hey Thanks Javier : )
        The download and install of quick-enroll agent worked on my vagrant test machine! Will test on the physical system as well and close this issue.

vagrant@vagrant:~$ curl -sk https://192.168.0.106/osquery-ubuntu-bionic/1c6IA8BJjXefBe88VWsWUR0PE6p/enroll.sh | sh 
[+] OS=linux
[+] _SECRET_FILE=/etc/osquery/osctrl-osquery-ubuntu-bionic.secret
[+] _FLAGS=/etc/osquery/osquery.flags
[+] _CERT=/etc/osquery/certs/osctrl-osquery-ubuntu-bionic.crt
[+] IMPORTANT! If osquery is not installed, it will be installed.
[+] [+] osctrl-osquery-ubuntu-bionic needs osquery
[+] Installing osquery for linux
[+] Installing osquery in Linux
[+] DEB based system detected
######################################################################## 100.0%
Selecting previously unselected package osquery.
(Reading database ... 42512 files and directories currently installed.)
Preparing to unpack .../osquery_4.2.0_1.linux.amd64.deb ...
Unpacking osquery (4.2.0-1.linux) ...
Setting up osquery (4.2.0-1.linux) ...
1351
Processing triggers for systemd (237-3ubuntu10.25) ...
Processing triggers for ureadahead (0.100.0-21) ...
[+] Stopping osqueryd
[+] Preparing osquery secret
5zHH-0WuQHNw8gjcSQxYaZ40G7LeqAEWy9c48FzF-ofo82flZhga2AoUjphG5mpKR8JvYnqWx18V2lrfczazPA==
[+] Preparing osquery flags
[+] Preparing osquery certificate
[+] Starting osqueryd
Synchronizing state of osqueryd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable osqueryd
Created symlink /etc/systemd/system/multi-user.target.wants/osqueryd.service → /usr/lib/systemd/system/osqueryd.service.
[+] Congratulations! The node has been enrolled in osctrl-osquery-ubuntu-bionic
[+] REMINDER! osqueryd has been started and enabled.

Thanks,
Avinash.

**Comment by avinashkurup** [comment] 2020-05-18 23:42
Hi Javier, A related matter to complete the above test. I have created a new environment and have created new certificates for it. The agent is downloaded and installed successfully, however the enrolled node is not shown up in the admin interface. Is there anything I'm missing? The dev environment is showing the nodes created in the ubuntu-vm container created by the make docker_all.

**Comment by javuto** [comment] 2020-05-19 02:11
I would look at the `osqueryd` logs and see what is happening. It sounds like the certificate could be invalid but better look at the logs to find out what is the problem.
